

GET http://localhost:2000/authorapi

###
POST http://localhost:2000/authorapi/newuser
Content-Type:application/json

{
    "usertype":"Author",
     "username":"prakash",
     "password":"prakash@04",
      "email":"prakash@gmail.com"
}

###
POST http://localhost:2000/authorapi/login
Content-Type:application/json

{
    "usertype":"author",
     "username":"prakash",
     "password":"prakash@04"
}

###
POST http://localhost:2000/authorapi/articles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InByYWthc2giLCJ1c2VydHlwZSI6IkF1dGhvciIsImlhdCI6MTc3MTM1Mzc5MywiZXhwIjoxNzcxNDQwMTkzfQ.HaPjEN4HEesmCth7X8UGSslA9LDI9bOmpqs7nVyzjOU

{
    "article_id":"{{$timestamp}}",
    "title":"Godavari",
    "category":"Movies",
    "img":"https://images.mubicdn.net/images/film/72582/cache-249603-1503290018/image-w1280.jpg",
    "content":"Godavari is a film about Sriram...",
    "date_creation":"{{$datetime iso8601}}",
    "date_modification":"{{$datetime iso8601}}",
    "username":"prakash",
    "comments":[],
    "status":true
}


###
PUT  http://localhost:2000/authorapi/articles
Content-Type:application/json

{
    "article_id":"1739295900",
     "title":"Javascript",
     "category":"Programming",
     "content":"It runs in web browsers and enables developers to build features such as form validation, interactive maps, animations, and much more",
     "date_creation":"2025-02-11T17:45:00.111Z",
     "date_modification":"{{$datetime iso8601}}",
     "username":"prakash",
      "comments":[],
      "status":true
}

###

PUT  http://localhost:2000/authorapi/articles/1739295900
Content-Type:application/json

{
    "article_id":"1739295900",
     "title":"Javascript",
     "category":"Programming",
     "content":"It runs in web browsers and enables developers to build features such as form validation, interactive maps, animations, and much more",
     "date_creation":"2025-02-11T17:45:00.111Z",
     "date_modification":"{{$datetime iso8601}}",
     "username":"prakash",
      "comments":[],
      "status":false
}


###
GET http://localhost:2000/authorapi/articles/prakash

###
GET  http://localhost:2000/authorapi/articles/id/1740480690

